config/routes.rb
Rails.application.routes.draw do
  # get 'startup/index'
  #resources :welcomes
  root 'welcomes#new', as: 'home'
  
  resources :songs
  resources :users
  resources :reviews, except: [:new]
  resources :recordings
  resources :artists
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/recordings/:id/reviews/new', to:'reviews#new', as:'new_review'

  get '/sessions/new', to:'sessions#new', as:'new_login'
  post '/login', to:'sessions#create', as:'login'
  get '/logout', to:'sessions#destroy', as:'logout'
  get '/search', to: 'recordings#search', as: 'recording_search'
  


end

app/models/recording.rb
class Recording < ApplicationRecord

has_many :reviews
has_many :users, through: :reviews
belongs_to :artist
belongs_to :song

require 'rest-client'
require 'json'



#Musix Match api url
$base_url = "https://api.musixmatch.com/ws/1.1/"

#api methods
$lyrics_search = "track.search"
$id_search = "track.lyrics.get"

#format url
$format_url = "?format=json&callback=callback"

#Search parameters 
# q -> Any word in the song title or artist name or lyrics
$search_parameter = "&q="
$id_search_parameter = "&track_id="
 

    def self.api_track_request(search_input)
        response = RestClient.get "https://api.musixmatch.com/ws/1.1/track.search?format=json&callback=callback&q_lyrics=#{search_input}" + ENV["LYRICS_API_KEY"]
        response_hash = JSON.parse(response.body)
        track_array = response_hash["message"]["body"]["track_list"]
        self.api_lyric_request(track_array)
    end
    
    def self.api_lyric_request(track_array)
        track_array.each do |track_hash|
            track = track_hash["track"]
            response = RestClient.get "https://api.musixmatch.com/ws/1.1/track.lyrics.get?format=json&callback=callback&track_id=" + track["track_id"].to_s + ENV["LYRICS_API_KEY"]
            response_hash = JSON.parse(response.body)
            lyrics = response_hash["message"]["body"]["lyrics"]["lyrics_body"]
            self.generate_recording(track, lyrics)
        end
    end
        
    def self.generate_recording(track, lyrics)
        if track["artist_name"]
            artist = Artist.find_or_create_by(name: track["artist_name"]) 
        end
        if track["track_name"]
            song = Song.find_or_create_by(name: track["track_name"], lyric: lyrics)
        end
        if track["track_edit_url"]
            Recording.find_or_create_by(link: track["track_edit_url"], artist_id: artist.id, song_id: song.id)
        end
    end
    # def self.generate_recording(track, lyrics)
    #     artist = Artist.find_or_create_by(name: track["artist_name"])
    #     song = Song.find_or_create_by(name: track["track_name"], lyric: lyrics)
    #     Recording.find_or_create_by(link: track["track_edit_url"], artist_id: artist.id, song_id: song.id)
    # end


    def self.find_recordings_by_lyric_content(search_term)
        self.all.select { |recording| recording.song.lyric.include?(search_term) }
    end

    def average_rating
        sum = self.reviews.uniq.sum do |review|
            review.rating
        end
        average = sum.to_f / self.reviews.uniq.count
        average.round(2)
    end

end #end of r class


# iterate through tracks_array to grab tracks ids
# find lyrics through track ids
# response_hash["message"]["body"]["track_list"][0]["track"]["track_id"]
# display lyrics to screen

app/controllers/recordings_controller.rb
class RecordingsController < ApplicationController

    def show
        @recording = Recording.find(params[:id])
        session[:rec_id] = @recording.id
    end

    def search
        @searched_recordings = []
        if params[:search] != ""
            Recording.api_track_request(params[:search])
            @searched_recordings = Recording.find_recordings_by_lyric_content(params[:search])
        end 

        render :search
    end


end #end of rc class

app/helpers/recordings_helper.rb
module RecordingsHelper
end

app/views/recordings/search.html.erb
<div class="songs">
<h1><%="Your Results"%></h1>

<% if @searched_recordings == [] %>
      <p style="font-family:geneva">Invalid input!</p>
<% else %>
      <ol>
      <% @searched_recordings.each do |recording| %>
            <li><p><%= link_to "#{recording.artist.name} | #{recording.song.name}", recording_path(recording) %></p></li>
      <% end %>
      </ol>
<% end %>

</div>

app/views/recordings/show.html.erb
<!DOCTYPE html>
<html>
<head>

<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.vinyl {
  
  
  
  width: 50%;
  height: 50%;
  -webkit-animation: spin 2s linear infinite; /* Safari */
  animation: spin 2s linear infinite;
}

/* Safari */
@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
</style>
</head>
<body>
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
      <h3><%= "Is this what you're looking for?" %></h3>
        <div class="vinyl"><img src="https://pngriver.com/wp-content/uploads/2018/04/Download-Vinyl-PNG-Image-1.png" alt="vinyl" width=100% height=100% ></div>
        <div class="star-rating" data-score= <@average_rating %></div>
        <em><%= "#{@recording.reviews.length} reviews"%></em>
        <div>
        <div class="stars">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
          <span class="fa fa-star checked"></span>
        <style>
          .checked {
            color: orange;
          }
        </style>
        </div>
          <table class="table">
            <tbody>
              <tr>
                <td><strong> Song Title:</strong></td>
                <td><%= @recording.song.name %></td>
              </tr>
                <td><strong> Artist Name: </strong></td>
                <td><%= @recording.artist.name %></td>
              </tr>
              <tr>
                <td><strong>Rating:</strong></td>
                <% if @recording.average_rating > 0 %>
                  <td><%= @recording.average_rating %></td>
                <% else %>
                  <td><%= "Not rated yet" %></td>
                <% end %>
              </tr>
              <tr>
                <td><strong> Lyrics: </strong></td>
                <td><%= simple_format(@recording.song.lyric) %></td>
              </tr>
                <%= link_to "View full lyrics", @recording.link, target: :_blank %>
              <% if logged_in? %>
                <p><%= link_to "Create Review", new_review_path %></p>
              <% else %>
                <p><%= link_to "Sign Up to Create Review", new_user_path %></p>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <div class="col-md-7 col-md-offset-1">
        <h3 class="review_title"><%= @recording.song.name %></h3>
        <p><%= @recording.artist.name %></p>

          <h4>Reviews: </h4>
            <% if @recording.reviews.blank? %>
              <p> No reviews yet! </p>
            <% else %>
              <% @recording.reviews.each do |review| %>
                <div class="reviews">
                  <div class="stars" data-score= <%= review.rating %> ></div>
                <p><%= review.description %></p>
              <% end %>
            <% end %>
          </ul>
      </div>
  </div>
</div>