config/routes.rb
Rails.application.routes.draw do
  # get 'startup/index'
  #resources :welcomes
  root 'welcomes#new', as: 'home'
  
  resources :songs
  resources :users
  resources :reviews, except: [:new]
  resources :recordings
  resources :artists
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/recordings/:id/reviews/new', to:'reviews#new', as:'new_review'

  get '/sessions/new', to:'sessions#new', as:'new_login'
  post '/login', to:'sessions#create', as:'login'
  get '/logout', to:'sessions#destroy', as:'logout'
  get '/search', to: 'recordings#search', as: 'recording_search'
  


end

app/models/song.rb
class Song < ApplicationRecord

has_many :recordings
has_many :artist, through: :recordings


end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

    def index
    end 


    def show
        @song = Song.find_by(params[:id])
    end 


    private

    def song_params
        params.require(:song).permit(:name, :lyric, :search)
    end

end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
body {
  background-color: lightblue;
}

<h1><%="Song Results"%></h1>


h1, h3 {
  text-align: center;
}
</style>
</head>
<body>

<h1><%="Here's the skinny:"%></h1>

<p><%= link_to "Search Bar", home_path %></p>

</body>
</html>

app/views/songs/show.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
body {
  background-color: lightblue;
}

h1, h3 {
  text-align: center;
}
</style>
</head>
<body>

<h1><%= "Show Page" %></h1>