config/routes.rb
Rails.application.routes.draw do
  # get 'startup/index'
  #resources :welcomes
  root 'welcomes#new', as: 'home'
  
  resources :songs
  resources :users
  resources :reviews, except: [:new]
  resources :recordings
  resources :artists
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/recordings/:id/reviews/new', to:'reviews#new', as:'new_review'

  get '/sessions/new', to:'sessions#new', as:'new_login'
  post '/login', to:'sessions#create', as:'login'
  get '/logout', to:'sessions#destroy', as:'logout'
  get '/search', to: 'recordings#search', as: 'recording_search'
  


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def index
        @reviews = Review.all 
    end

    def show
        @review = Review.find(params[:id])
        @reviews = Review.all
    end

    def new
        @review = Review.new 
        @rec_id = session[:rec_id]
        @review_recording = Recording.find(@rec_id)
    end

    def create
        @user = User.find_by(id: session[:user_id])

        @rec_id = session[:rec_id]
        @new_review = Review.create(review_params)


       # Review.create(rating: 1, user_id: @user_id, recording_id:  @rec_id, description: "The Beach Boys are a revelation.")

        params[:recording_id] = @rec_id
 
        @user.my_reviews << @new_review
         
    
        redirect_to recording_path(@rec_id)
    end


    # def create
    #     @user = User.find_by(id: session[:user_id])
    #     @rec_id = session[:rec_id]
    #     @new_review = Review.create(review_params)
    #     params[:recording_id] = @rec_id
    #     @user.my_reviews << @new_review
    #     redirect_to recording_path(@new_review.recording)
    # end



    def destroy
        @review.destroy
    end

    private

    def review_params
        params.require(:review).permit(:rating, :description, :recording_id)
    end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
body {
  background-color: lightblue;
}

h1, h3, h4 {
  text-align: center;
}
</style>
</head>
<body>

<h1>Reviews Index</h1>
<br>
<br>

<h4><% @reviews.each do |review| %>
    <%= "#{review.rating}. #{review.description}" %></h4>
<% end %>

<!-- <p><%= link_to "Create your review", new_review_path %></p> -->

app/views/reviews/new.html.erb
<!DOCTYPE html>
<html>
<head>

<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.vinyl {
  width: 10%;
  height: 10%;
  display: block;
  margin-left: auto;
  margin-right: auto;
  margin-bottom: 15px;
  -webkit-animation: spin 2s linear infinite; 
  padding-bottom: 15px;
}

/* Safari */
@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

.review {
    text-align: center;
  }
.col-md-7.col-md-offset-1 {
  text-align:top;
}
</style>
</head>

<div class="vinyl"><img src="https://pngriver.com/wp-content/uploads/2018/04/Download-Vinyl-PNG-Image-1.png" alt="vinyl" width=100% height=100% ></div>

<div class="review">
<% if logged_in? %>
    <%= form_for @review do |f| %>
        <%= f.label :rating %><br>
        <%= f.number_field :rating, min: 1, max: 5 %><br><br>

        <%= f.label :description, "What's stuck in your mind?" %><br>
        <%= f.text_area :description %><br>

        <%= f.label :recording_id, "Track ID"%><br>
        <%= f.number_field :recording_id, value: @rec_id %><br><br>

        <%= f.submit "Create Review" %>
    <% end %>
    <br>
<% else %>
    <li><%= link_to "Sign Up to review", new_user_path %></li>
    <li ><%= link_to "Sign In to review", new_login_path %></li>
<% end %>
</div>

<div class="col-md-7 col-md-offset-1">
  <h3 class="review_title"><%= @review_recording.song.name %></h3>
  <p><%= @review_recording.artist.name %></p>
    <h4>Reviews: </h4>
      <% if @review_recording.reviews.blank? %>
        <p> No reviews yet! </p>
      <% else %>
        <% @review_recording.reviews.each do |review| %>
          <div class="reviews">
            <div class="stars" data-score= <%= review.rating %> ></div>
          <p><%= review.description %></p>
        <% end %>
      <% end %>
    </ul>
</div>

app/views/reviews/show.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
body {
  background-color: lightblue;
}

h1, h3 {
  text-align: center;
}
</style>
</head>
<body>

<h1>Reviews Page: </h1>
 <ul>
        <% @user.reviews.each do |review| %>
        <% song_review = review.recording.song_id %>
        <li><%= link_to Song.find(song_review).name, recording_path(review.recording_id) %></li>
        <p><%= review.recording.artist.name %></p>
        <p><li><%= "#{review.description} | #{review.rating}" %></li></p>
        <% end %>
    </ul>

</body>
</html>