config/routes.rb
Rails.application.routes.draw do
  # get 'startup/index'
  #resources :welcomes
  root 'welcomes#new', as: 'home'
  
  resources :songs
  resources :users
  resources :reviews, except: [:new]
  resources :recordings
  resources :artists
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/recordings/:id/reviews/new', to:'reviews#new', as:'new_review'

  get '/sessions/new', to:'sessions#new', as:'new_login'
  post '/login', to:'sessions#create', as:'login'
  get '/logout', to:'sessions#destroy', as:'logout'
  get '/search', to: 'recordings#search', as: 'recording_search'
  


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord

has_many :recordings
has_many :songs, through: :recordings

end

app/models/recording.rb
class Recording < ApplicationRecord

has_many :reviews
has_many :users, through: :reviews
belongs_to :artist
belongs_to :song

require 'rest-client'
require 'json'



#Musix Match api url
$base_url = "https://api.musixmatch.com/ws/1.1/"

#api methods
$lyrics_search = "track.search"
$id_search = "track.lyrics.get"

#format url
$format_url = "?format=json&callback=callback"

#Search parameters 
# q -> Any word in the song title or artist name or lyrics
$search_parameter = "&q="
$id_search_parameter = "&track_id="
 

    def self.api_track_request(search_input)
        response = RestClient.get "https://api.musixmatch.com/ws/1.1/track.search?format=json&callback=callback&q_lyrics=#{search_input}" + ENV["LYRICS_API_KEY"]
        response_hash = JSON.parse(response.body)
        track_array = response_hash["message"]["body"]["track_list"]
        self.api_lyric_request(track_array)
    end
    
    def self.api_lyric_request(track_array)
        track_array.each do |track_hash|
            track = track_hash["track"]
            response = RestClient.get "https://api.musixmatch.com/ws/1.1/track.lyrics.get?format=json&callback=callback&track_id=" + track["track_id"].to_s + ENV["LYRICS_API_KEY"]
            response_hash = JSON.parse(response.body)
            lyrics = response_hash["message"]["body"]["lyrics"]["lyrics_body"]
            self.generate_recording(track, lyrics)
        end
    end
        
    def self.generate_recording(track, lyrics)
        if track["artist_name"]
            artist = Artist.find_or_create_by(name: track["artist_name"]) 
        end
        if track["track_name"]
            song = Song.find_or_create_by(name: track["track_name"], lyric: lyrics)
        end
        if track["track_edit_url"]
            Recording.find_or_create_by(link: track["track_edit_url"], artist_id: artist.id, song_id: song.id)
        end
    end
    # def self.generate_recording(track, lyrics)
    #     artist = Artist.find_or_create_by(name: track["artist_name"])
    #     song = Song.find_or_create_by(name: track["track_name"], lyric: lyrics)
    #     Recording.find_or_create_by(link: track["track_edit_url"], artist_id: artist.id, song_id: song.id)
    # end


    def self.find_recordings_by_lyric_content(search_term)
        self.all.select { |recording| recording.song.lyric.include?(search_term) }
    end

    def average_rating
        sum = self.reviews.uniq.sum do |review|
            review.rating
        end
        average = sum.to_f / self.reviews.uniq.count
        average.round(2)
    end

end #end of r class


# iterate through tracks_array to grab tracks ids
# find lyrics through track ids
# response_hash["message"]["body"]["track_list"][0]["track"]["track_id"]
# display lyrics to screen

app/models/review.rb
class Review < ApplicationRecord

belongs_to :user
belongs_to :recording

end

app/models/song.rb
class Song < ApplicationRecord

has_many :recordings
has_many :artist, through: :recordings


end

app/models/user.rb
class User < ApplicationRecord
has_many :my_reviews, foreign_key: "user_id", class_name: "Review"
has_many :reviews
has_many :recordings, through: :reviews
has_secure_password 
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def index
        @reviews = Review.all 
    end

    def show
        @review = Review.find(params[:id])
        @reviews = Review.all
    end

    def new
        @review = Review.new 
        @rec_id = session[:rec_id]
        @review_recording = Recording.find(@rec_id)
    end

    def create
        @user = User.find_by(id: session[:user_id])

        @rec_id = session[:rec_id]
        @new_review = Review.create(review_params)


       # Review.create(rating: 1, user_id: @user_id, recording_id:  @rec_id, description: "The Beach Boys are a revelation.")

        params[:recording_id] = @rec_id
 
        @user.my_reviews << @new_review
         
    
        redirect_to recording_path(@rec_id)
    end


    # def create
    #     @user = User.find_by(id: session[:user_id])
    #     @rec_id = session[:rec_id]
    #     @new_review = Review.create(review_params)
    #     params[:recording_id] = @rec_id
    #     @user.my_reviews << @new_review
    #     redirect_to recording_path(@new_review.recording)
    # end



    def destroy
        @review.destroy
    end

    private

    def review_params
        params.require(:review).permit(:rating, :description, :recording_id)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # skip_before_action :authorized, only: [:new, :create]

  def reset_page_count
    session.delete(:page_count)
    redirect_back fallback_location: home_path
  end

  def new
    
  end
  
  def create
    @user = User.find_by(username: params[:session][:username])
    
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:error] = "Incorrect username/password"
      redirect_to new_login_path
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to home_path
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

    def index
    end 


    def show
        @song = Song.find_by(params[:id])
    end 


    private

    def song_params
        params.require(:song).permit(:name, :lyric, :search)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :find_user, only: [:show, :edit, :update, :destroy]

    def show
    end
    
    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        if @user.valid?
            session[:user_id] = @user.id

            flash[:success] = "Congratulations! Successfully created your profile!"
            redirect_to user_path(@user)
        else
            flash[:errors] = @user.errors.full_messages
            redirect_to new_user_path
        end
    end

    def edit
    end

    def update
        if @user.update(user_params)
            redirect_to user_path(@user)
        else
            flash[:errors] = @user.errors.full_messages
            redirect_to edit_user_path(@user)
        end
    end

    def destroy
        @user.destroy
        
        redirect_to home_path
    end

    private

    def find_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation, :age, :country, :img_url)
    end

end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController

    def new
        @song = Song.new
        @songs = Song.all 
    end 

    def create
        @song = Song.create(params[:id])
        redirect_to song_path(@song)
    end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/recordings_helper.rb
module RecordingsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/startup_helper.rb
module StartupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "MusicLyricSearch", home_path, class: "navbar-brand" %>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <% if logged_in? %>
                    <li><%= link_to "Log Out", logout_path %></li>
                    <li><%= link_to "Account", logged_in_user %></li>       
                <% else %>
                    <li><%= link_to "Sign Up", new_user_path %></li>
                    <li><%= link_to "Sign In", new_login_path %></li>
                <% end %>
            </ul>
            <%= form_tag recording_search_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
                <p>
                    <%= text_field_tag :search, params[:search], placeholder: "Enter word/phrase", class: "form-control" %>
                    <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
                </p>
            <% end %>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicLyricSearch</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

 <style>  
    body, h1, h2, h3, h4, h5, p, table, .button_to {
      font-family: geneva, sans-serif;
      font-weight: 100;
    }    
    .site-footer
      {
        background-color:#26272b;
        padding:45px 0 20px;
        font-size:15px;
        line-height:24px;
        color:#737373;
        margin-top:380px;

      }
    .copyright-text
      {
        margin:0;
        padding-left: 15px
      }
      @media (max-width:991px)
      {
    .site-footer [class^=col-]
      {
          margin-bottom:5px
      }
      }
    @media (max-width:767px)
      {
    .site-footer
      {
        padding-bottom:0
      }
    .site-footer .copyright-text
      {
        text-align:center
      }
      }

      .songs {
        padding-left: 10%;
        padding-right: 10%;
      }
       </style>  

</head>
<body>

      <%= render 'layouts/header' %>
      
        <% flash.each do |name, msg| %>
          <%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>

<%= yield %>
<%# <footer class="site-footer">
  <p class="copyright-text">Copyright &copy; 2020 All Rights Reserved by 
    <a href="#">MusicLyricSearch</a>.
  </p>
 
</footer> %>
</body>
</html>